on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: deploy

jobs:
  deploy:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Prepare HTMLs to deploy
        run: |
          mkdir -p _deploy
          mkdir -p _deploy/day1_RNA_velocity_slides
          cp day1_RNA_velocity/RNAVelocitySlides.html _deploy/day1_RNA_velocity_slides/index.html
          cp -r day1_RNA_velocity/libs day1_RNA_velocity/images day1_RNA_velocity/rna-velocity-figures _deploy/day1_RNA_velocity_slides
          cp day1_RNA_velocity/my-macros.js day1_RNA_velocity/my-theme.css day1_RNA_velocity/insert-logo-title.html _deploy/day1_RNA_velocity_slides
          cp day1_python_and_R/01_introduction.html _deploy/day1_python_and_R__01_introduction.html
          cp day2_experimental_approaches/Smallwood_Advanced_SC_Analysis_Basel_2022.pdf _deploy/day2_experimental_approaches__Smallwood_Advanced_SC_Analysis_Basel_2022.pdf
          mkdir -p _deploy/day3_interactive_visualization_iSEE_slides
          cp day3_interactive_visualization_iSEE/slides.html _deploy/day3_interactive_visualization_iSEE_slides/index.html
          cp -r day3_interactive_visualization_iSEE/libs day3_interactive_visualization_iSEE/images day3_interactive_visualization_iSEE/screenshots _deploy/day3_interactive_visualization_iSEE_slides
          cp day3_interactive_visualization_iSEE/my-macros.js day3_interactive_visualization_iSEE/my-theme.css day3_interactive_visualization_iSEE/insert-logo-title.html _deploy/day3_interactive_visualization_iSEE_slides

      - name: Deploy ðŸš€
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _deploy
